services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

