services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: dockerization/Dockerfile
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - '8000:8000'
    volumes:
      - users_files:/users_files
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: dockerization/nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80" 

volumes:
  db:
    driver: local
  users_files:


